#!/bin/bash


NAME=qinstaller
MAIN=http://188.165.193.139:8888

grep -e "\[PRODUCER_NAME\]" \
     -e "\[PRODUCER_PUBLIC_KEY\]" \
     -e "\[PRODUCER_PRIVATE_KEY\]" \
     -e "\[SERVER_ADDRESS\]" /etc/$NAME/config.ini

if [ $? -eq 0 ]; then
    if [ "$(id -u)" -ne 0 ]
        then echo "Please run as root to run config setup for qinstaller"
        exit 1
    fi

    while [ -z $PRODNAME ]; do
        read -p "Enter producer name: " PRODNAME
    done
    while [ -z $PUBKEY ]; do
        read -p "Enter producer public key: " PUBKEY
    done
    while [ -z $PRIVKEY ]; do
        read -p "Enter producer private key: " PRIVKEY
    done
    while [ -z $SERVER ]; do
        read -p "Enter server address: " SERVER
    done

    echo "Checking if account with pubkeys exists..."
    cleos -u $MAIN  get account $PRODNAME | grep $PUBKEY
    if [ $? -ne 0 ]; then
        echo "Account $PRODNAME with pubkey $PUBKEY does not exist, aborting..."
        exit 1
    fi

    echo "Registering producer node..."
#    cleos wallet create -n testnet --file /tmp/password_for_testnet_wallet
#    cleos wallet open -n testnet
#    cleos wallet unlock -n testnet < /tmp/password_for_testnet_wallet
#    cleos wallet import -n testnet --private-key $PRIVKEY
    cleos -u $MAIN system regproducer $PRODNAME $PUBKEY
#    if [ $? -ne 0 ]; then
#        echo "Unable to perform registration of validator, aborting..."
#        exit 1
#    fi

    sed -i "s/\[PRODUCER_NAME\]/$PRODNAME/g" /etc/$NAME/config.ini
    sed -i "s/\[PRODUCER_PUBLIC_KEY\]/$PUBKEY/g" /etc/$NAME/config.ini
    sed -i "s/\[PRODUCER_PRIVATE_KEY\]/$PRIVKEY/g" /etc/$NAME/config.ini
    sed -i "s/\[SERVER_ADDRESS\]/$SERVER/g" /etc/$NAME/config.ini

fi

nodeos --config-dir /etc/$NAME/ --delete-all-blocks -e --protocol-features-dir=/tmp/$NAME/protocol_features/ --genesis-json /etc/$NAME/genesis.json --disable-replay-opts
