#!/bin/bash

IMG_NAME="docker_quantra"
RUN_MODE="text"
# This is required, cause old distros may not have UID, GID envs
U_ID=$(id -u)
G_ID=$(id -g)


usage() {
  echo "Usage: $0 [ -g ]" 1>&2
}


QUANTRA_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    --)
      shift
      break
      ;;
    *)
      QUANTRA_ARGS+=("$1") 
      shift
      ;;
  esac
done

while getopts ":g" options; do
  case "${options}" in
    g)
      RUN_MODE="gui"
      break
      ;;
    *)
      usage
      exit 2
      ;;
  esac
done

if which podman 2>/dev/null >&2; then
    CONTAINER_RUNTIME=podman
elif which docker 2>/dev/null >&2; then
    CONTAINER_RUNTIME=docker
else
    echo "'docker' or 'podman' command is not found. Please install docker or podman first"; exit 1;
    exit 1
fi

$CONTAINER_RUNTIME inspect $IMG_NAME &> /dev/null || \
    { echo "$IMG_NAME container not available. Please, run install_quantra_docker.sh first"; exit 1; }


if [[ "$RUN_MODE" == "gui" ]]; then

    echo "Running quantra GUI mode"
    $CONTAINER_RUNTIME run \
                           -e DISPLAY \
                           -e XAUTHORITY \
                           -v /run/user/$U_ID/:/run/user/$U_ID:ro \
                           -v /home/$USER/.quantra:/root/.quantra:rw \
                           -v /dev/bus/usb:/dev/bus/usb \
                           --rm \
                           --net=host \
                           --privileged \
                           --entrypoint "/usr/bin/quantra-gui" \
                           $IMG_NAME ${QUANTRA_ARGS[*]}
else
    echo "Running quantra console mode"
    $CONTAINER_RUNTIME run \
                           -v /home/$USER/.quantra:/root/.quantra:rw \
                           -v /dev/bus/usb:/dev/bus/usb \
                           --rm \
                           --net=host \
                           --privileged \
                           --interactive \
                           --tty \
                           --entrypoint "/usr/bin/quantra" \
                           $IMG_NAME ${QUANTRA_ARGS[*]}
fi

exit 0
