#!/bin/bash

IMG_NAME="docker_quantra"


if ! command -v docker -v &> /dev/null
then
    echo "'docker' command is not found. Please install it first"
    exit 1
fi

docker run -u=$UID:$GID \
           --uidmap $UID:0:1 \
           --uidmap 0:1:$UID \
           -e DISPLAY \
           -e XAUTHORITY \
           -v /home/$USER/.Xauthority:/home/$USER/.Xauthority:ro \
           -v /run/user/$UID/:/run/user/$UID:ro \
           -v /home/$USER/.quantra:/home/$USER/.quantra:rw \
           --rm \
           --net=host \
           --privileged \
           --entrypoint "/usr/bin/quantra-gui" \
           $IMG_NAME "$@"
